### ISSUE TITLE
Etapa 1: Duda convención de señales

### ISSUE THREAD

**Issue by jlizamajara** [IIC2343/Syllabus-2023-2#43]
Hola! Estoy teniendo un problema con el programa y creo que es por la manera en que defino las señales de entrada y salida de componentes. ¿Existe una convención para ello?

Muchas gracias de antemano! 🌼

**Comment by frvalenzuela** [comment]
Hola! 

No estoy seguro a que te refieres con convención. Pero es igual a como lo definimos en las actividades de laboratorio. Cada entidad tiene entradas y salidas que puedes ser vectores o unidad lógicas. 

Saludos!
