### ISSUE TITLE
Duda de enunciado

### ISSUE THREAD

**Issue by dasobarzo** [IIC2343/Syllabus-2023-2#6]
Hola! en la actividad 1 leí en una función del recorrer(self, kilometros) de la clase vehículo, que dice "Método abstracto, que obliga a las clases hijas a que este método sea implementado." a que refiere esto? entiendo que las clases hijas serían Bencina, eléctrico, etc... pero que debería retornar esto o como darme cuenta, porque en verdad no lo entiendo.

**Comment by frvalenzuela** [comment]
Hola @dasobarzo !

Creo que te equivocaste de curso.

Saludos!
