### ISSUE TITLE
Etapa 3: Aumentar +1 apretando un boton

### ISSUE THREAD

**Issue by JSalas277** [IIC2343/Syllabus-2023-2#78]
Estoy desarrollando el segundo juego, y al igual que el anterior dispuse de un modo de espera:

modo_espera:
MOV A, (3) # Se guarda en A la direccion de los botones
MOV (2), A # Se guarda en el Display la direccion de los botones
MOV B, (1) # Se guarda en B la direccion de los switches
AND B, 32768 # Se ve si el primer bit de B es igual al primer bit de 32768 (1)
JNE activar_juego #Si no es igual a 0, entonces se activa el juego
JMP modo_espera #Si es igual a cero, se mantiene en modo de espera

Pero ahora lo que quiero hacer es que en vez de que cada boton tenga un valor, quiero que todos los botones vayan agregando mas uno cada vez que los aprietas. ¿Mas o menos que tengo que tener en mente para llevarlo a cabo aqui?

**Comment by Geeermy** [comment]
Hola.

Por favor, nunca compartas código de tus desarrollos por issues, se ve como una falta a la ética. Si necesitas hacerlo, pregunta de forma directa a tus ayudantes.

Saludos.
